version: '3'
services:
    redis:
        image: redis:4.0.6-alpine
        ports:
          - "6379:6379"
        volumes:
            - ./redis:/redis

    flask-app:
        image: messages.prepwithmo
        container_name: messages.prepwithmo
        build:
          context: .
          dockerfile: Dockerfile.Service.Local
        env_file:
            - ./DockerEnv
        extra_hosts:
            - "host:192.168.1.135"
        restart: always
        ports:
            - '5003:5003'
        volumes:
            - ./app:/app

    worker:
        image: messages.prepwithmo:latest
        depends_on:
            - redis
        extra_hosts:
            - "host:192.168.1.135"
        env_file:
            - ./DockerEnv
        command: rq worker --url redis://redis:6379
        links:
            - redis
